get_ready: get_up eat_breakfast make_bed brush_teeth
	echo "Dad, I'm ready to go to school" > get_ready

make_bed: get_up
	echo "You made your bed" > make_bed

brush_teeth: eat_breakfast
	echo "You brushed your teeth" > brush_teeth

eat_breakfast: get_up
	echo "You ate breakfast" > eat_breakfast

get_up:
	echo "You got up" > get_up
